mysite/urls.py
from django.urls import include,path
from django.contrib import admin

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/',admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results/',views.ResultsView.as_view(),name='result'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    # was_published_recently.admin_order_field = 'pub_date'
    # was_published_recently.boolean = True
    # was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse,HttpResponseRedirect
from django.http import Http404
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
        

class DetailView(generic.DetailView):
    model = Question
    template_name = 'detail.html'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
        


class ResultsView(generic.DetailView):
    model = Question
    template_name='results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:detail', args=(question.id,)))
    
    

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>
		{% block title %}
		  
		{% endblock title %}
	</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'polls/style.css' %}">

</head>
<body>
	<div class="container">
		<div class="col-md-3 col-md-offset-4">
			{% block content %}
			  
			{% endblock content %}
		</div>
	</div>
	<!-- jQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<!-- Bootstrap JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% block title %}
  Polls | Polls-app
{% endblock title %}
{% block content %}
         {% if error_message %}
        <p>
            <strong>{{ error_message }}</strong>
        </p>{%endif%}
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="fa fa-line-chart"></span> {{ question.question_text}}</h3>
            </div>
            <div class="panel-body">
                <center>
                <form action="{% url 'polls:vote' question.id%}" method="post">
                    {% csrf_token %} {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice {{forloop.counter }}" value="{{ choice.id }}" />
                    <label for="choice {{forloop.counter }}">{{choice.choice_text }}</label><br>
                    {% endfor %}
                    <input type="submit" name="" value="Vote"><br>
                    <a href="{% url 'polls:result' question.id %}" class="small">View Result</a>
                </center>
            </div>
        </div>
{% endblock content %}

templates/index.html
{% extends "base.html" %} {% block title %} Home | Polls-app {% endblock title %} {% block content %}


<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="fa fa-line-chart"></span> Choose your poll</h3>
    </div>
    <div class="panel-body">
         {% if latest %}
        <ul class="list-group">
             {% for question in latest %}
            <li class="list-group-item">
                
                    <label>
                        <a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>
                    </label>
                
            </li>
             {% endfor %}
            
        </ul>
         {% else %}
        <p>Oops!!!No polls are available.Contact your administrator</p>
        {% endif %}
    </div>
    
</div>
{% endblock content %} 

templates/results.html
{% extends "base.html" %}
{% block title %}
Results | Polls-app  
{% endblock title %}

{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">
            <span class="fa fa-line-chart"></span> Results of {{ question.question_text}}</h3>
    </div>
    <div class="panel-body">
        <center>
           
            
                {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                {% endfor %}
             
            
            <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
        </center>
    </div>
</div>
{% endblock content %}